add Circle
ministryofjustice/cloud-platform-user-docs pull request #46
Opened 2018-06-05 15:55 UTC by razvan-moj

2018-06-06 20:44 UTC, kalbir requested changes
The key things to change are:

1. The formatting (backticks)
2. A bullets that need to be deleted
3. Long version of commands 

I _think_ we might need to say a bit more in places, I've asked @nayoa to take a look as well.

2018-06-06 20:44 UTC, kalbir commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> + - You have a basic understanding of what [Kubernetes](https://kubernetes.io/) is.
Let's delete this bullet, by the time you read this guide you'll know or you'll be very lost.

2018-06-06 20:44 UTC, kalbir commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> + - You have [deployed an application](https://ministryofjustice.github.io/cloud-platform-user-docs/02-deploying-an-app/001-app-deploy-helm/#tutorial-deploying-an-application-to-the-cloud-platform-wit
Deploying an application depends on having installed `kubectl` and authenticated to the cluster so we can get rid of those two bullet and keep the one that says "you have deployed an application".

2018-06-06 20:44 UTC, kalbir commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +  NAME       SECRETS   AGE
1. I think it would be good to leave a line between each command-output pair for each bash command. I think this makes it a little easier to read on the screen. 

2. Can you use the long form of the kubernetes commands e.g. `kubectl get serviceaccounts --namespace <example-namespace>`?

2018-06-06 20:44 UTC, kalbir commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +We are using CircleCI 2.0 if you already have a CircleCI circle.yml please [migrate](https://circleci.com/docs/2.0/migration/) your project to 2.0.
Could you put file names and directory names in backticks "`" -- this makes them identifiable as "code" items and easier to read. 

I think the main ones are `config.yml` and `.circleci`.

2018-06-06 20:44 UTC, kalbir commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +- TOKEN
Could you explain where each of these environment variables comes from? My understanding is the first 4 are from the ECR repo creation process and the last 3 are Kubernetes secrets, how do you get those? 

Also could you put the names of the env variables in backticks.

2018-06-06 20:44 UTC, kalbir commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +- Run tests
Did you want to have these first 4 bullet points? They seem to be lacking a purpose here.

2018-06-07 10:14 UTC, nayoa commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +A Service Account is created in the [namespace creation github repository](https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces).
I reckon developers may ask about what to include in a service account. Could use this one as an example - https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/non-production.k8s.integration.dsd.io/reference-app/serviceaccount-circleci.yaml

2018-06-07 10:22 UTC, nayoa commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +```
Think there's a new naming convention for tagging docker images. https://github.com/ministryofjustice/cloud-platform-reference-app/blob/master/.circleci/config.yml#L45

2018-06-07 10:36 UTC, nayoa commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +- TOKEN
May need to explain that you need to have the base64 decoded token and the encoded ca_cert saved as an environment variable. ca_cert will be decoded during the build.

2018-06-07 10:38 UTC, nayoa commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +```
Think this has slightly changed in master to - https://github.com/ministryofjustice/cloud-platform-reference-app/blob/master/.circleci/config.yml#L63

Biggest change is replicacount = 4

2018-06-07 10:42 UTC, nayoa commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +[Tutorial](https://circleci.com/docs/2.0/tutorials/) on creating a config.yml file. The cloud platform reference app, has the following steps. As long as you are build a docker image you can configur
Would be interesting to have an example config.yml in the doc.

2018-06-07 10:42 UTC, nayoa commented on 02-deploying-an-app/004-use-circleci-to-upgrade-app.md
> +- Run tests
Would be good to add how to authenticate with the cluster. https://github.com/ministryofjustice/cloud-platform-reference-app/blob/master/.circleci/config.yml#L21

2018-06-07 14:47 UTC, nayoa commented
LGTM

2018-06-07 14:48 UTC, nayoa approved these changes
LGTM

2018-06-08 09:57 UTC, kalbir approved these changes

2018-06-08 10:20 UTC, merged