kubectl quick reference document
ministryofjustice/cloud-platform-user-docs pull request #50
Opened 2018-07-12 11:53 UTC by alkar

2018-07-12 12:07 UTC, alkar commented
I'm not sure that `{:toc}` will work.

2018-07-12 16:04 UTC, kalbir requested changes
The table of contents doesn't work (I've shown how to fix it) but do we actually need it?

2018-07-12 16:04 UTC, kalbir commented on 03-other-topics/003-quick-reference.md
> +{:toc}
Yeah this doesnt work. You can add any aribtrary list immediately before it to make it work:

```
* TOC
{:toc}
```

That works.

*However* you also get a table of contents autogenerated in the left panel of the page, so do you need two of them?

<img width="1364" alt="screen shot 2018-07-12 at 16 52 50" src="https://user-images.githubusercontent.com/3952074/42644658-090d2560-85f4-11e8-988c-68dbb8727257.png">

2018-07-12 16:04 UTC, kalbir commented on 03-other-topics/003-quick-reference.md
> +{:toc}
...and as I can now see from looking at the screenshot (isn't it weird how looking at a screenshot is so different to looking at your _screen_?) the table of contents that is generated contains the page title and `table of contents` as a heading. You can remove this by adding a `no_toc` class to the heading, which in `Kramdown` you do like the following:

```
# Kubernetes quick reference
{:.no_toc}

```

⬆️ that will stop "Kubernetes quick reference" showing up.

2018-07-12 16:04 UTC, kalbir commented on 03-other-topics/003-quick-reference.md
> +{:toc}
Actually, turns out that in turn breaks the way the side contents works 
<img width="1364" alt="screen shot 2018-07-12 at 17 03 16" src="https://user-images.githubusercontent.com/3952074/42645254-7e4dae98-85f5-11e8-8d77-c7d79b7fbdb1.png">

So I'm even less convinced we need the contents inline (I don't know how to fix this problem!)

2018-07-13 09:17 UTC, alkar commented
We definitely do not need an inline TOC - I just forgot that we get the sidebar TOC by default. Removed.

2018-07-16 13:04 UTC, kalbir approved these changes
Yep that's better without the table of contents

2018-07-16 15:56 UTC, merged