dynamodb doc
ministryofjustice/cloud-platform-user-docs pull request #63
Opened 2018-09-06 10:14 UTC by razvan-moj

2018-09-06 10:20 UTC, jasonBirchall commented on 02-deploying-an-app/008-add-dynamodb-to-your-app.md
> +  $ git co -b add_dynamodb   # create and checkout new branch.
not a big issue but this is an alias.

2018-09-10 10:26 UTC, jasonBirchall requested changes
Just a few changes. 
Also, is it worth putting the, 'how to get your db instance name' instructions in here?

2018-09-10 10:26 UTC, jasonBirchall commented on 02-deploying-an-app/008-add-dynamodb-to-your-app.md
> +sddsf
assuming this is a typo?

2018-09-10 10:26 UTC, jasonBirchall commented on 02-deploying-an-app/008-add-dynamodb-to-your-app.md
> +asa
And here.

2018-09-10 10:26 UTC, jasonBirchall commented on 02-deploying-an-app/008-add-dynamodb-to-your-app.md
> +4\. Create your module and change the module name and input variables. More instructions [here](https://github.com/ministryofjustice/cloud-platform-terraform-dynamodb-cluster). Follow the example dir
More instructions here is pretty empty.

2018-09-10 10:34 UTC, jasonBirchall approved these changes

2018-09-10 14:45 UTC, merged

2018-09-10 14:54 UTC, alkar commented on 02-deploying-an-app/008-add-dynamodb-to-your-app.md
> +    name = "${module.dynamodb.table_name}"
`terraform fmt` please!

2018-09-10 14:54 UTC, alkar commented on 02-deploying-an-app/008-add-dynamodb-to-your-app.md
> +The DB name will be present in the k8s secret, or if used outside the CP pipeline, create an output.tf file:
The "out of pipeline" use can be confusing?
Do we really need it?